# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 256)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self._2.setObjectName("_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self._2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._2.addItem(spacerItem)
        self._3 = QtWidgets.QFormLayout()
        self._3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self._3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self._3.setObjectName("_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self._3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self._3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self._3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self._3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self._3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self._3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self._2.addLayout(self._3)
        spacerItem1 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._2.addItem(spacerItem1)
        self._4 = QtWidgets.QHBoxLayout()
        self._4.setObjectName("_4")
        self.buttonSave = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSave.setObjectName("buttonSave")
        self._4.addWidget(self.buttonSave)
        self.buttonView = QtWidgets.QPushButton(self.centralwidget)
        self.buttonView.setObjectName("buttonView")
        self._4.addWidget(self.buttonView)
        self._2.addLayout(self._4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание питомца"))
        self.label.setText(_translate("MainWindow", "Создание питомца"))
        self.label_2.setText(_translate("MainWindow", "Имя питомца"))
        self.label_3.setText(_translate("MainWindow", "Возраст питомца"))
        self.label_4.setText(_translate("MainWindow", "Вид"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Кот/Кошка"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Пёс/Собака"))
        self.buttonSave.setText(_translate("MainWindow", "Сохранить"))
        self.buttonView.setText(_translate("MainWindow", "Просмотреть"))
